---
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: indexfondsenvergelijken
  name: indexfondsenvergelijken

spec:
  replicas: 1

  selector:
    matchLabels:
      app: indexfondsenvergelijken

  template:
    metadata:
      labels:
        app: indexfondsenvergelijken

    spec:
      containers:
        - name: indexfondsenvergelijken
          image: ghcr.io/nicwortel/indexfondsenvergelijken.nl:latest
      imagePullSecrets:
        - name: github-container-registry
